# Generated by Django 2.0 on 2020-09-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du campus')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom Falcute')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prenom')),
                ('date', models.DateField(verbose_name='Date de naissance')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationalite')),
                ('sex', models.CharField(max_length=20, verbose_name='Sex')),
                ('civil_status', models.CharField(max_length=30, verbose_name='Etat civil')),
                ('diploma', models.CharField(max_length=50, verbose_name='Diplome')),
                ('level', models.CharField(max_length=50, verbose_name='Niveau')),
                ('cni', models.CharField(max_length=40, verbose_name="Carte d'identite")),
                ('email', models.CharField(max_length=50, verbose_name='Adresse email')),
                ('phone', models.IntegerField(max_length=60, verbose_name='Numero de telephone')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='student_inscription.Campus', verbose_name='Campus')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='student_inscription.Faculty', verbose_name='Faculte')),
            ],
        ),
    ]
