# Generated by Django 2.0 on 2020-09-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(verbose_name='Numero de telephone'),
        ),
    ]
